### ISSUE TITLE
Please add 'allow-forms' and 'allow-modals' attributes in the iframe sandbox. 

### ISSUE THREAD

**Issue by amitgrd16** [benwilcock/backstage-plugin-backchat#4]
Hi,
I am getting below error while using Ollama GUI using backstage-backchat-plugins .
"Blocked form submission to '' because the form's frame is sandboxed and the 'allow-forms' permission is not set."
"The document is sandboxed, and the 'allow-modals' keyword is not set."
Please add 'allow-forms' and 'allow-modals' attributes in the iframe sandbox. 

Regards,
Amit

**Comment by benwilcock** [comment]
All done. Thanks!
